Django/simple_social_clone/simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views #django login and logout views
from . import views

app_name = 'accounts' #needed for url templates

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'), #uses django view so no need to assign template_name
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
]

Django/simple_social_clone/simplesocial/groups/urls.py
#Groups url.py file

from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$', views.ListGroups.as_View(), name='all'),
    url(r'^new/$', views.CreateGroup.as_View(), name='create'),
    url(r'posts/in/(?P<slug>[-\w]+)/$', views.SingleGroup.as_View(), name='single'),
    
]

Django/simple_social_clone/simplesocial/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.UserPosts.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete')
]

Django/simple_social_clone/simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
]

Django/simple_social_clone/simplesocial/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

Django/simple_social_clone/simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify #remove characters

# Create your models here.
import misaka #link mark down text like reddit. Install using pip install misaka
from django.contrib.auth import get_user_model # return active user model for project
User = get_user_model() # call things off current user session
from django import template
register = template.Library() # allows us to use custom template tags

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    member = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs{'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(model.Model):
    group = models.ForeignKey(Group, related_name='memberships')
    user = models.ForeignKey(User, related_name='user_group')

    def __str__(self):
        return self.user.username

    class Meta():
        uique_together = ('group','user')


    pass

Django/simple_social_clone/simplesocial/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

import misaka

from groups.models import Group
# Create your models here.
# POSTS models.py

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':slef.user.username, 'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

Django/simple_social_clone/simplesocial/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


# user sign up form class
class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name' #set the labels to display on the form
        self.fields['email'].label = 'Email Address'

Django/simple_social_clone/simplesocial/accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView

from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm # grab the form data in forms.py
    success_url = reverse_lazy('login') # on successfull signup, send user back to login page
    template_name = 'accounts/signup.html'

Django/simple_social_clone/simplesocial/groups/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin PermissionRequiredMixin

from django.core.urlresolvers import reverse
from django.views import generic
from .models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

Django/simple_social_clone/simplesocial/posts/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model # allows you to set User variable like below
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin

from . import models
from . import forms

# Create your views here.
User = get_user_model() #allows you to use current user object

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user','group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    #try to get posts for the user
    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_releated('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.usr.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

Django/simple_social_clone/simplesocial/simplesocial/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

Django/simple_social_clone/simplesocial/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div class="container">
    <h1>Login</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class='btn btn-default' value="Login">
    </form>

  </div>
{% endblock %}

Django/simple_social_clone/simplesocial/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div class="container">
    <h1>Signup</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class='btn btn-default' value="Sign Up">
    </form>

  </div>
{% endblock %}

Django/simple_social_clone/simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
      {% block pregoup %}{% endblock %}
      {% block group_content %}{% endblock %}
      {% block postgroup %}{% endblock %}  
  </div>

</div>

{% endblock %}

Django/simple_social_clone/simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}

<h1>{{group.name}}</h1>
<h2>Member Count: {{group.members.count}}</h2>

<div class="content">

  {% if user in group.members.all %}
    <a href="{% url 'groups.leave' slug=group.slug %}" class='btn btn-lg btn-fill btn-warning'><span class='glyphicon glyphicon-remove-circle'></span>Leave</a>

  {% else %}
    <a href="{% url 'groups.join' slug=group.slug %}" class='btn btn-lg btn-fill btn-warning'><span class='glyphicon glyphicon-ok-circle'></span>Join</a>
  {% endif %}

</div>

{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h2>No Posts in this group yet</h2>

  {% else %}
    {% for post in group.posts.all %}
      {% include "posts/_post.html" %} <!-- extends or inject html file -->

    {% endfor %}

  {% endif %}
</div>

{% endblock %}

Django/simple_social_clone/simplesocial/groups/templates/groups/group_form.html
{% extends "groups/groups_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a new group</h4>
<form action="{% url groups:create' %}" method="post" id='groupForm'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit"  class='btn btn-primary btn-large' value="Create">
</form>

{% endblock %}

Django/simple_social_clone/simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block  pregroup %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
      <h2>Welcome Back <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a></h2>

    {% endif %}
    <h2>Groups</h2>
    <p>Welcome to groups page.</p>
  </div>

{% if user.is_authenticated %}
  <a href="{% url 'groups:create' %}" class='btn btn-md btn-fill btn-warning'>
    <span class='glyphicon glyphicon-plus-sign'>Create New Group!</span>
  </a>

{% endif %}

</div>
{% endblock %}

{% block group_content %}
  <div class="col-md-8">
    <div class="list-group">
      {% for group in object_list %}
        <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}">
          <h3 class='title list-group-item-heading'>{{group.name}}</h3>
          <div class="list-group-item-text container-fluid">
            {{group.description_html|safe}} <!-- use safe to ensure format carries over ie: bold text -->
            <div class="row">
              <div class="col-md-4">
                <span class='badge'>{{group.members.count}}</span>
                member{{group.members.count|pluralize}}

              </div>
              <div class="col-md-4">
                <span class='badge'>{{group.posts.count}}</span>
                post{{group.posts.count|pluralize}}
              </div>
            </div>
          </div>
        </a>

      {% endfor %}

    </div>
  </div>
{% endblock %}

Django/simple_social_clone/simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}"> <!-- look in static directory and load -->
  </head>
  <body>
    <nav class='navbar mynav' role='navigation' id='navbar'>
      <div class="container">
        <a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a href="#">Post</a></li>
            <li><a href="#">Groups</a></li>
            <li><a href="#">Create Group</a></li>
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="#">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li> <!--use urls.py accounts label -->
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}

        </ul>

      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

Django/simple_social_clone/simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Index.html page</h1>
{% endblock %}

Django/simple_social_clone/simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

Django/simple_social_clone/simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}